### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ResponseTooLong', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.19.1/src/behaviour.rs:282

### ISSUE THREAD

**Issue by CrackerHax** [stafiprotocol/stafi-node#3]
2020-07-31 03:11:23 Stafi Node
2020-07-31 03:11:23 ✌️  version 0.1.1-745f0f7-x86_64-linux-gnu
2020-07-31 03:11:23 ❤️  by Stafi Technologies <technical@stafi.io>, 2019-2020
2020-07-31 03:11:23 📋 Chain specification: Stafi Testnet Seiya
2020-07-31 03:11:23 🏷  Node name: furtive-month-4162
2020-07-31 03:11:23 👤 Role: FULL
2020-07-31 03:11:23 💾 Database: RocksDb at ~/.local/share/stafi/chains/stafi_public_testnet/db
2020-07-31 03:11:23 ⛓  Native runtime: node-254 (stafi-node-0.tx1.au10)
2020-07-31 03:11:24 🔨 Initializing Genesis block/state (state: 0x987c…eaf5, header-hash: 0xd224…475c)
2020-07-31 03:11:24 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
2020-07-31 03:11:25 ⏱  Loaded block-time = 6000 milliseconds from genesis on first-launch
2020-07-31 03:11:25 👶 Creating empty BABE epoch changes on what appears to be first startup.
2020-07-31 03:11:25 📦 Highest known block at #0
2020-07-31 03:11:25 〽️ Prometheus server started at 127.0.0.1:9615

====================

Version: 0.1.1-745f0f7-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/libstd/panicking.rs:490
   2: rust_begin_unwind
             at /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/libstd/panicking.rs:388
   3: core::panicking::panic_fmt
             at /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/libcore/panicking.rs:101
   4: core::option::expect_none_failed
             at /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/libcore/option.rs:1272
   5: <libp2p_mdns::behaviour::Mdns as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   6: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   7: <sc_network::behaviour::Behaviour<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   8: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler,TConnInfo>::poll_next_event
   9: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
  10: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  11: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  12: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: std::thread::local::LocalKey<T>::with
  15: futures_executor::local_pool::block_on
  16: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::runtime::blocking::pool::Inner::run
  19: tokio::runtime::context::enter
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
  22: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/liballoc/boxed.rs:1076
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/liballoc/boxed.rs:1076
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/libstd/sys/unix/thread.rs:87
  23: start_thread
  24: __clone

**Comment by Tore19** [comment]
Fixed

**Comment by singulart** [comment]
any suggestion how to fix this ?
